### PR TITLE
Added new model 'switch' that is a Switch. As opposed to Lightbulbs.

### PR DESCRIPTION
**Pull request by JakobPetersson**
It is certainly useful to get an accurate display in the Home app as well as correct voice control commands using siri.

Am, unsure if the name of the model fits with the already existing ones. Please tell me what you think.

### CODE REVIEW

**Comment by mifi** [comment]
Why did you close it?

**Comment by JakobPetersson** [comment]
Sorry to give mixed signals, I must have done it accidentally.

**Comment by mifi** [comment]
Ok, I think this sounds like a nice addition if you just want a generic switch, thanks.

**Comment by mifi** [comment]
Btw, have you tested that it works? If so, then we can make a new release.

**Comment by JakobPetersson** [comment]
Yes I have tested it in my own setup.

**Comment by mifi** [comment]
ReleaEd version 0.0.9

**Pull request merged**
